# Generated by Django 3.2.3 on 2021-05-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_response_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='avatar',
            field=models.CharField(blank=True, max_length=5150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='background',
            field=models.CharField(blank=True, max_length=5150, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cancel_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='confirm_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1550),
        ),
        migrations.AlterField(
            model_name='event',
            name='password',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='response',
            name='guest_name',
            field=models.CharField(max_length=350),
        ),
    ]
